repos:
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    additional_dependencies: [tomli]
    exclude: ^test/fixtures/

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.0
  hooks:
  - id: ruff
    args: ["--fix"]
    exclude: ^git/ext/
  - id: ruff-format
    exclude: ^git/ext/

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
    args: [--color]
    exclude: ^test/fixtures/polyglot$|^git/ext/

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: end-of-file-fixer
    exclude: ^test/fixtures/|COPYING|LICENSE
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: check-merge-conflict

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.19
  hooks:
  - id: validate-pyproject
